In [9]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent = [
    "I loved the movie",              # Positive
    "The acting was great",           # Positive
    "What a boring film",             # Negative
    "I will never watch this again",  # Negative
    "Absolutely fantastic experience",# Positive
    "Worst direction and plot",       # Negative
    "Such a beautiful performance",   # Positive
    "The story made no sense",        # Negative
    "Highly recommended to all",      # Positive
    "It was a waste of time"          # Negative
]


In [15]:
sent


['I loved the movie',
 'The acting was great',
 'What a boring film',
 'I will never watch this again',
 'Absolutely fantastic experience',
 'Worst direction and plot',
 'Such a beautiful performance',
 'The story made no sense',
 'Highly recommended to all',
 'It was a waste of time']

In [45]:
#define the vocab size
voc_size=10000

In [47]:
##ohe rep
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr ## these are index where the word is located 

[[7613, 2732, 1487, 3700],
 [1487, 8616, 9786, 5708],
 [1385, 7869, 1188, 6227],
 [7613, 9686, 3845, 232, 6532, 5376],
 [5935, 4132, 2196],
 [8686, 4032, 6915, 4758],
 [4071, 7869, 4802, 975],
 [1487, 1971, 5413, 4416, 4752],
 [1118, 1025, 2436, 734],
 [5512, 9786, 7869, 7396, 4568, 2259]]

In [49]:
##word embedding layer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [51]:
import numpy as np

In [53]:
## at the end in rnn we send fixed number of words in a sentences with its timestamp so we use pad _seq
sent_length=8 #so max wrd size is 8 so make em all 8 itll add 0 either in pre or post ofthe senteces
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 7613 2732 1487 3700]
 [   0    0    0    0 1487 8616 9786 5708]
 [   0    0    0    0 1385 7869 1188 6227]
 [   0    0 7613 9686 3845  232 6532 5376]
 [   0    0    0    0    0 5935 4132 2196]
 [   0    0    0    0 8686 4032 6915 4758]
 [   0    0    0    0 4071 7869 4802  975]
 [   0    0    0 1487 1971 5413 4416 4752]
 [   0    0    0    0 1118 1025 2436  734]
 [   0    0 5512 9786 7869 7396 4568 2259]]


In [55]:
##feature repr ___ to make it into that dim for the word embeddong
dims=10


In [57]:
model=Sequential()
model.add(Embedding(voc_size,dims,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.predict(embedded_docs) ##so alll wrds in sentences is rep in 10 dim vector
#foreach wrd in a sentence id gotrep as 10d vector


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[ 2.36763470e-02, -3.09308525e-02, -9.97638702e-03,
         -1.38689056e-02, -8.35835934e-04,  4.17584181e-03,
          3.09374221e-02,  4.80516069e-02,  2.17379965e-02,
          1.96065567e-02],
        [ 2.36763470e-02, -3.09308525e-02, -9.97638702e-03,
         -1.38689056e-02, -8.35835934e-04,  4.17584181e-03,
          3.09374221e-02,  4.80516069e-02,  2.17379965e-02,
          1.96065567e-02],
        [ 2.36763470e-02, -3.09308525e-02, -9.97638702e-03,
         -1.38689056e-02, -8.35835934e-04,  4.17584181e-03,
          3.09374221e-02,  4.80516069e-02,  2.17379965e-02,
          1.96065567e-02],
        [ 2.36763470e-02, -3.09308525e-02, -9.97638702e-03,
         -1.38689056e-02, -8.35835934e-04,  4.17584181e-03,
          3.09374221e-02,  4.80516069e-02,  2.17379965e-02,
          1.96065567e-02],
        [-4.33824435e-02, -4.55453992e-02, -2.58157849e-02,
         -3.31374630e-02, -2.94858217e-02,  3.37263010e-02,
          1.05645061e-02, -2.15969216e-02,  3.941375

Position   Token ID   Embedding Vector (10-D)
--------   --------   ------------------------
[0]        0          [ 0.0236, -0.0309, ..., 0.0196 ]
[1]        0          [ 0.0236, -0.0309, ..., 0.0196 ]
[2]        0          [ 0.0236, -0.0309, ..., 0.0196 ]
[3]        0          [ 0.0236, -0.0309, ..., 0.0196 ]
[4]     7613          [-0.0433, -0.0455, ..., -0.0244 ]
[5]     2732          [-0.0321, -0.0414, ..., -0.0101 ]
[6]     1487          [-0.0127,  0.0347, ...,  0.0121 ]
[7]     3700          [-0.0355,  0.0241, ...,  0.0056 ]
